package py.com.abiti.esystem.egym.view;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.annotations.Theme;
import com.vaadin.event.ShortcutAction;
import com.vaadin.event.ShortcutListener;

import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.CustomLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.LoginForm.LoginEvent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import com.vaadin.ui.themes.ValoTheme;

import py.com.abiti.esystem.egym.event.EventBus;
import py.com.abiti.esystem.egym.jpa.JpaUsuario;
import py.com.abiti.esystem.egym.util.JpaUtil;
import py.com.abiti.esystem.egym.util.UserUtil;



/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
@Theme("mytheme")
public class LoginView extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout loginLayout;
	@AutoGenerated
	private LoginForm loginEva;
	

	private Window window;
	
	private TextField txtUsuario;
	private PasswordField txtpass;
	
	private Button btnIngresar;
	
	

	private JpaUsuario jpaUsuario = new JpaUsuario(JpaUtil.getEntityManagerFactory());
	
	public LoginView() {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		crearComponentes();
		
		//loginEva.setUsernameCaption("Funcionario");
		//loginEva.setPasswordCaption("Constraseña");
		
		//loginEva.addLoginListener(event -> loggear(event));
		
		btnIngresar.addClickListener(e -> ingresar(txtUsuario.getValue(), txtpass.getValue()));
		
		txtUsuario.focus();
		
		
		
		txtpass.addShortcutListener(new ShortcutListener("entrar", ShortcutAction.KeyCode.ENTER, null) {
			@Override
			public void handleAction(Object sender, Object target) {
				
				
			
				//ingresar(txtUsuario.getValue(), txtpass.getValue());
				if (target.equals(txtUsuario)) {
					
					txtpass.focus();
					
				}
				
				if (target.equals(txtpass)) {
					
					ingresar(txtUsuario.getValue(), txtpass.getValue());
					
				}
				
			}
		});
		
		Panel loginPanel = new Panel("Login");
		CustomLayout content = new CustomLayout("loginLayout");
		content.setSizeUndefined();
		loginPanel.setContent(content);
		loginPanel.setSizeUndefined();
		
		content.addComponent(txtUsuario, "username");
		content.addComponent(txtpass, "password");
		content.addComponent(btnIngresar, "okbutton");
		
		mainLayout.addComponent(loginPanel);
		mainLayout.setComponentAlignment(loginPanel, Alignment.MIDDLE_CENTER);
		
	}
	
	
	/*
	 * 	Panel loginPanel = new Panel("Login");
		CustomLayout content = new CustomLayout("layoutname");
		content.setSizeUndefined();
		loginPanel.setContent(content);
		loginPanel.setSizeUndefined();
		
		// No captions for fields is they are provided in the template
		content.addComponent(new TextField(), "username");
		content.addComponent(new TextField(), "password");
		content.addComponent(new Button("Login"), "okbutton");
	 */
		
		
		/*textField.addShortcutListener(new ShortcutListener("Shortcut Name", ShortcutAction.KeyCode.ENTER, null) {
			@Override
			public void handleAction(Object sender, Object target) {
				// your code here
			}
		});
		
		
		
		//imagen.setSource(new ThemeResource("images/cabeceraImagen.png"));
		
		//txtUsuario.addBlurListener(e -> buscarFoto() );
		
		
	}
	/*private void buscarFoto() {
		
		Usuario usuFoto = jpaUsuario.findUsuarioByUser(txtUsuario.getValue());
		if (usuFoto != null) {
			
			if (usuFoto.getPersona() != null) {
				
				File arch = new File(usuFoto.getPersona().getFoto());
				
				imagen.setSource(new FileResource(arch));
				
			}else {
				
				imagen.setSource(new ThemeResource("images/cabeceraImagen.png"));
				
			}
			
			
		}else {
			
			imagen.setSource(new ThemeResource("images/cabeceraImagen.png"));
			
		}
		
	}*/
	
	private void crearComponentes() {

		txtUsuario = new TextField();
		txtpass = new PasswordField();

		
		
		btnIngresar = new Button();
		btnIngresar.setCaption("Ingresar");
		btnIngresar.setStyleName(ValoTheme.BUTTON_PRIMARY);
		
		
	}


	private void ingresar(String usuario, String clave) {
		
		String pass;
		String user;
		boolean ingresar;
		
		//pass = evento.getLoginParameter("password").toString();
		//user = evento.getLoginParameter("username").toString();
		
		pass = clave;
		user = usuario;
		
		
		if (pass == "") {
			Notification.show("Debe ingresar la contraseña", Notification.Type.ERROR_MESSAGE);
			return;
		}
		
		if (user == "") {
			Notification.show("Debe ingresar el usuario", Notification.Type.ERROR_MESSAGE);
			return;
		}
		
		ingresar = jpaUsuario.login(user, pass);
		if (ingresar) {
			
		/*	//Notification.show("Adelante");
			FuncionariosView funView = new FuncionariosView();
			Window ventana = new Window("Funcionarios", funView);
			ventana.center();
			ventana.setResizable(true);
			ventana.setModal(true);
			UI.getCurrent().addWindow(ventana);*/
			//EventBus.post(new py.com.tipcsa.eva.event.LoginEvent(jpaUsuario.findUsuario(5)));
			//EventBus.post(new py.com.tipcsa.eva.event.LoginEvent());
			EventBus.post(new py.com.abiti.esystem.egym.event.LoginEvent(jpaUsuario.findUsuarioByUser(user)));
			UserUtil.set(jpaUsuario.findUsuarioByUser(user));
			UserUtil.setUsuario(jpaUsuario.findUsuarioByUser(user));
			//  EventBus.post(py.com.tipcsa.eva.event.LoginEvent(jpaUsuario.findUsuarioByUser(user)));
			//EvaUI.getCurrent().getNavigator().navigateTo("");
			
			
		}else {
			Notification.show("Usuario o contraseña incorrectos", Notification.Type.ERROR_MESSAGE);
		}
		
		
		
	}
	private void loggear(LoginEvent evento) {
	
		
		String pass;
		String user;
		boolean ingresar;
		
		pass = evento.getLoginParameter("password").toString();
		user = evento.getLoginParameter("username").toString();
		
		if (pass == "") {
			Notification.show("Debe ingresar la contraseña", Notification.Type.ERROR_MESSAGE);
			return;
		}
		
		if (user == "") {
			Notification.show("Debe ingresar el usuario", Notification.Type.ERROR_MESSAGE);
			return;
		}
		
		ingresar = jpaUsuario.login(user, pass);
		if (ingresar) {
			
		/*	//Notification.show("Adelante");
			FuncionariosView funView = new FuncionariosView();
			Window ventana = new Window("Funcionarios", funView);
			ventana.center();
			ventana.setResizable(true);
			ventana.setModal(true);
			UI.getCurrent().addWindow(ventana);*/
			//EventBus.post(new py.com.tipcsa.eva.event.LoginEvent(jpaUsuario.findUsuario(5)));
			//EventBus.post(new py.com.tipcsa.eva.event.LoginEvent());
			EventBus.post(new py.com.abiti.esystem.egym.event.LoginEvent(jpaUsuario.findUsuarioByUser(user)));
			UserUtil.set(jpaUsuario.findUsuarioByUser(user));
			UserUtil.setUsuario(jpaUsuario.findUsuarioByUser(user));
			//  EventBus.post(py.com.tipcsa.eva.event.LoginEvent(jpaUsuario.findUsuarioByUser(user)));
			//EvaUI.getCurrent().getNavigator().navigateTo("");
			
			
		}else {
			Notification.show("Usuario o contraseña incorrectos", Notification.Type.ERROR_MESSAGE);
		}
		
		
		
		
		
		
		
	}
	
	
	public void setWindow(Window window){
		this.window = window;
	}

	
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100%");
		
		// loginLayout
		
		//mainLayout.addComponent(loginLayout);
		//mainLayout.setComponentAlignment(loginLayout, Alignment.MIDDLE_CENTER);
		
		
		/*mainLayout.setComponentAlignment(loginLayout, Alignment.MIDDLE_CENTER);
		mainLayout.setComponentAlignment(loginLayout, new Alignment(50));*/
		
		
		
		return mainLayout;
	}

	

	
	
	
	
	
	
	
	
	
	
}
