package py.com.abiti.esystem.egym.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;

import py.com.abiti.esystem.egym.EgymUI;
import py.com.abiti.esystem.egym.util.LazyProvider;
import py.com.abiti.esystem.egym.util.MyTheme;
import py.com.abiti.esystem.egym.util.NavigationBar;
import py.com.abiti.esystem.egym.util.PageTitleUpdater;
import py.com.abiti.esystem.egym.util.ViewConfig;




public class Main extends HorizontalLayout {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private static final Class<? extends View> Persona = null;

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	
	private NavigationBar navigationBar;
	private Navigator navigator;
	private Panel content;
	
	
	public Main() {
		
		addStyleName(MyTheme.MAIN_LAYOUT);
		
		setSizeFull();
		
		initLayouts();
		SetupNavigator();
		
		
	}
	
	
	private void initLayouts() {

	 	navigationBar = new NavigationBar();
        // Use panel as main content container to allow it's content to scroll
        content = new Panel();
        content.setSizeFull();
        content.addStyleName(MyTheme.PANEL_BORDERLESS);

        addComponents(navigationBar, content);
        setExpandRatio(content, 1);
	
	}
	
	
	private void registerViews() {
		
		
		addHiddenView(PrincipalView.class);
		addHiddenView(AltaProductoView.class);
		addHiddenView(AltaCuentaView.class);
		addHiddenView(AltaPersonaView.class);
		addHiddenView(AltaClienteView.class);
		addHiddenView(AltaCliente.class);
	

		//addHiddenView(viewClass);
		/*addHiddenView(AltaPersonaView.class);
		addHiddenView(UsuarioView.class);
		addHiddenView(AltaProveedorView.class);
		addHiddenView(AltaMarcaView.class);
		/*addHiddenView(PersonaAbmView.class);
		addHiddenView(AltaPersonaView.class);
		addHiddenView(AltaReunionView.class);
		addHiddenView(ReunionAbmView.class);
		addHiddenView(HanView.class);
		addHiddenView(AltaHanView.class);
		addHiddenView(PersonaHanView.class);*/
		navigationBar.addMenuTitle("Administracion");
		//addView(AltaPersonaView.class);
		
	}
	
	private void SetupNavigator() {
		
		navigator = new Navigator(EgymUI.getCurrent(), content);
		
		registerViews();
		
		navigator.addViewChangeListener(navigationBar);
		navigator.addViewChangeListener(new PageTitleUpdater());
		
		navigator.navigateTo(navigator.getState());
		
	}
	
	private void addHiddenView(Class<? extends View> viewClass){
		ViewConfig viewConfig = viewClass.getAnnotation(ViewConfig.class);
		
		switch (viewConfig.createMode()) {
			case ALWAYS_NEW:
				navigator.addView(viewConfig.uri(), viewClass);
				break;
			case LAZY_INIT:
				navigator.addProvider(new LazyProvider(viewConfig.uri(),viewClass));
				break;
			case EAGER_INIT:
				try {
					navigator.addView(viewConfig.uri(), viewClass.newInstance());
				} catch (Exception e) {
					e.printStackTrace();
				}
		
		}
		
	}
	
	private void addView(Class<? extends View> viewClass) {
        ViewConfig viewConfig = viewClass.getAnnotation(ViewConfig.class);

        switch (viewConfig.createMode()) {
            case ALWAYS_NEW:
                navigator.addView(viewConfig.uri(), viewClass);
                break;
            case LAZY_INIT:
                //navigator.addProvider(new LazyProvider(viewConfig.uri(), viewClass));
                break;
            case EAGER_INIT:
//                try {
//                    navigator.addView(viewConfig.uri(), viewClass.newInstance());
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
        }
        navigationBar.addView(viewConfig.uri(), viewConfig.displayName());
    }
	
	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new AbsoluteLayout();
	}
	
	
	
	
	
	
	

}
